# Easy_matryoshka by yfNSN
version: "2"

services:

  web:
    build: .
    image: yfnsn/ijuns_secret_bbs
    environment:
      - FLAG=flag{test_flag}
    restart: always
    ports:
      - "127.0.0.1:8302:80"